Train:
  batch_size: 128
  learning_rate: 0.1
  reg: 0.0005
  epochs: 10
  steps: [6, 8]
  warmup: 0
  momentum: 0.9

network:
  model: TwoLayerNet # TwoLayerNet or VanillaCNN or MyModel or ResNet-32

data:
  imbalance: regular # regular or imbalance
  save_best: True

loss:
  loss_type: CE # CE or Focal
